### ISSUE TITLE
App crash when call 'OtaUpdate().execute'

### ISSUE THREAD

**Issue by scofield-hello** [4Q-s-r-o/ota_update#13]
E/AndroidRuntime( 7534): FATAL EXCEPTION: Thread-2
E/AndroidRuntime( 7534): Process: com.chuangdun.cysy, PID: 7534
E/AndroidRuntime( 7534): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-2
E/AndroidRuntime( 7534): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime( 7534): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/AndroidRuntime( 7534): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/AndroidRuntime( 7534): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:151)
E/AndroidRuntime( 7534): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:144)
E/AndroidRuntime( 7534): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
E/AndroidRuntime( 7534): 	at sk.fourq.otaupdate.OtaUpdatePlugin$2.run(OtaUpdatePlugin.java:179)
E/AndroidRuntime( 7534): 	at java.lang.Thread.run(Thread.java:764)

--------------------------
flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.7.1, on Microsoft Windows [Version 10.0.17763.503], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[!] VS Code, 64-bit edition (version 1.34.0)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.

-----------------------

**Comment by scofield-hello** [comment]
I fixed it by modify OtaUpdatePlugin.java:

```java
    private Handler handler;

    private OtaUpdatePlugin(final Registrar registrar) {
        this.registrar = registrar;
        Context context = (registrar.activity() != null) ? registrar.activity() : registrar.context();
        handler = new Handler(context.getMainLooper()){
            @Override
            public void handleMessage(Message msg) {
                super.handleMessage(msg);
                if (progressSink != null) {
                    progressSink.success(Arrays.asList("" + OtaStatus.DOWNLOADING.ordinal(), "" + ((msg.arg1 * 100) / msg.arg2)));
                }
            }
        };
    }

    private void trackDownloadProgress(final long downloadId, final DownloadManager manager) {
         ......
         int bytes_downloaded = c.getInt(c.getColumnIndex(DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR));
                    int bytes_total = c.getInt(c.getColumnIndex(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));
                    if (progressSink != null) {
                        Message message = new Message();
                        message.arg1 = bytes_downloaded;
                        message.arg2 = bytes_total;
                        handler.sendMessage(message);
                        /*progressSink.success(Arrays.asList("" + OtaStatus.DOWNLOADING.ordinal(), "" + ((bytes_downloaded * 100) / bytes_total)));*/
                    }
                ......
    }
```
