### ISSUE TITLE
Please fix!

### ISSUE THREAD

**Issue by Nightwelf** [4Q-s-r-o/ota_update#17]
Samsung Galaxy J3(2017) Android 9

```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at sk.fourq.otaupdate.OtaUpdatePlugin$1.handleMessage(OtaUpdatePlugin.java:61)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7188)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by MartinHlavna** [comment]
Hi,

can you provide output from flutter doctor? Looks like this can happen when android download manager returns COLUMN_TOTAL_SIZE_BYTES = 0.

Solutions is to not publish progress in this case.

**Comment by MartinHlavna** [comment]
Hotfix will be releasing in 2.0.2. But i would still like to investigate a bit further.

**Comment by MartinHlavna** [comment]
It may be related to #16
