### ISSUE TITLE
Failed to open event stream

### ISSUE THREAD

**Issue by RomeroYang** [4Q-s-r-o/ota_update#30]
This error occurred when i call `OtaUpdate().execute(url)`:

```plaintext
D/FLUTTER OTA(  438): OTA UPDATE ON LISTEN
E/EventChannel#sk.fourq.ota_update(  438): Failed to open event stream
E/EventChannel#sk.fourq.ota_update(  438): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/EventChannel#sk.fourq.ota_update(  438): 	at sk.fourq.otaupdate.OtaUpdatePlugin.onListen(OtaUpdatePlugin.java:98)
E/EventChannel#sk.fourq.ota_update(  438): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
E/EventChannel#sk.fourq.ota_update(  438): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/EventChannel#sk.fourq.ota_update(  438): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/EventChannel#sk.fourq.ota_update(  438): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/EventChannel#sk.fourq.ota_update(  438): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#sk.fourq.ota_update(  438): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/EventChannel#sk.fourq.ota_update(  438): 	at android.os.Looper.loop(Looper.java:174)
E/EventChannel#sk.fourq.ota_update(  438): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/EventChannel#sk.fourq.ota_update(  438): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#sk.fourq.ota_update(  438): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/EventChannel#sk.fourq.ota_update(  438): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel sk.fourq.ota_update:
PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:517:29)
#4      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:64)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

and this is my `GeneratedPluginRegistrant.java` file:
```java
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      com.smallbuer.flutter_aes_ecb_pkcs5.FlutterAesEcbPkcs5Plugin.registerWith(shimPluginRegistry.registrarFor("com.smallbuer.flutter_aes_ecb_pkcs5.FlutterAesEcbPkcs5Plugin"));
    flutterEngine.getPlugins().add(new com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin());
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
      me.hetian.flutter_qr_reader.FlutterQrReaderPlugin.registerWith(shimPluginRegistry.registrarFor("me.hetian.flutter_qr_reader.FlutterQrReaderPlugin"));
      com.flutter_webview_plugin.FlutterWebviewPlugin.registerWith(shimPluginRegistry.registrarFor("com.flutter_webview_plugin.FlutterWebviewPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
      sk.fourq.otaupdate.OtaUpdatePlugin.registerWith(shimPluginRegistry.registrarFor("sk.fourq.otaupdate.OtaUpdatePlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.packageinfo.PackageInfoPlugin());
    flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
  }
}
```
and `flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/shawn/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shawn/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by RomeroYang** [comment]
It seems to be an issue related to simulator, it finished downloading on my real device.

**Comment by RomeroYang** [comment]
But there's another problem:
```
OtaStatus.DOWNLOADING : 100
D/AndroidRuntime(30150): Shutting down VM
E/AndroidRuntime(30150): FATAL EXCEPTION: main
E/AndroidRuntime(30150): Process: io.polkawallet.www.polka_wallet, PID: 30150
E/AndroidRuntime(30150): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=io.polkawallet.www.polka_wallet (has extras) } in sk.fourq.otaupdate.OtaUpdatePlugin$2@3b3f42a
E/AndroidRuntime(30150): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
E/AndroidRuntime(30150): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime(30150): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(30150): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(30150): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(30150): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/AndroidRuntime(30150): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30150): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(30150): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(30150): Caused by: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority io.polkawallet.www.polka_wallet.ota_update_provider
E/AndroidRuntime(30150): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/AndroidRuntime(30150): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/AndroidRuntime(30150): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/AndroidRuntime(30150): 	at sk.fourq.otaupdate.OtaUpdatePlugin$2.onReceive(OtaUpdatePlugin.java:190)
E/AndroidRuntime(30150): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
E/AndroidRuntime(30150): 	... 8 more
E/MQSEventManagerDelegate(30150): failed to get MQSService.
```
