### ISSUE TITLE
When installing, there was a crash and exit problem

### ISSUE THREAD

**Issue by BedRockGx** [4Q-s-r-o/ota_update#54]
Hi：
In the Android real mobile phone environment, after I downloaded the APK file using the plug-in, the APK file could not be opened automatically, and the App crashed. The specific reasons for the error are as follows:

E/AndroidRuntime(17033): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.example.financial_choice (has extras) } in sk.fourq.otaupdate.OtaUpdatePlugin$2@dc692f4
E/AndroidRuntime(17033):        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
E/AndroidRuntime(17033):        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime(17033):        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(17033):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(17033):        at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(17033):        at android.app.ActivityThread.main(ActivityThread.java:7560)
E/AndroidRuntime(17033):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17033):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(17033):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(17033): Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=content://com.example.financial_choice.ota_update_provider/external_download/ZeRong flg=0x10000001 }  
E/AndroidRuntime(17033):        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2066)
E/AndroidRuntime(17033):        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1720)
E/AndroidRuntime(17033):        at android.app.Activity.startActivityForResult(Activity.java:5260)
E/AndroidRuntime(17033):        at android.app.Activity.startActivityForResult(Activity.java:5218)
E/AndroidRuntime(17033):        at android.app.Activity.startActivity(Activity.java:5589)
E/AndroidRuntime(17033):        at android.app.Activity.startActivity(Activity.java:5557)
E/AndroidRuntime(17033):        at sk.fourq.otaupdate.OtaUpdatePlugin$2.onReceive(OtaUpdatePlugin.java:262)
E/AndroidRuntime(17033):        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
E/AndroidRuntime(17033):        ... 8 more
E/MQSEventManagerDelegate(17033): failed to get MQSService.
D/JIGUANG-JCommon-P(17033): [JCommonInterface] onEvent action:deviceinfo
D/JIGUANG-JCore-P(17033): [HttpHelper] status code:200 retry left:2
I/Process (17033): Sending signal. PID: 17033 SIG: 9

**Comment by BedRockGx** [comment]
The following is my current flutter version. It is worth noting that it was used in version 1.22.0, which can be downloaded and installed normally.

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1440], locale zh-CN)
    • Flutter version 1.22.5 at E:\flutter_1.22.5\flutter
    • Framework revision 7891006299 (4 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = D:\Android
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)

**Comment by ethael** [comment]
Hi there. We are able to support only the latest stable flutter release. Currently 2.0.x, therefore I am closing this ticket for now. If you will be able to reproduce on 2.0.x, feel free to reopen the issue. Don't forget to use the latest version of the ota_update plugin.
