### ISSUE TITLE
No Activity found to handle Intent

### ISSUE THREAD

**Issue by 645638180** [4Q-s-r-o/ota_update#81]
Download is complete then crash

D/FLUTTER OTA(28049): STREAM OPENED
D/DecorView[](28049): onWindowFocusChanged hasWindowFocus false
D/FLUTTER OTA(28049): REQUEST PERMISSIONS RESULT RECEIVED
D/FLUTTER OTA(28049): DOWNLOAD STARTING
D/DecorView[](28049): onWindowFocusChanged hasWindowFocus true
I/HandWritingStubImpl(28049): isKeyboardTypeChanged: false
I/HandWritingStubImpl(28049): refreshLastKeyboardType: 1
I/HandWritingStubImpl(28049): getCurrentKeyboardType: 1
I/HandWritingStubImpl(28049): isKeyboardTypeChanged: false
D/FLUTTER OTA(28049): Download is complete
D/AndroidRuntime(28049): Shutting down VM
E/AndroidRuntime(28049): FATAL EXCEPTION: main
E/AndroidRuntime(28049): Process: com.songxing.songxing, PID: 28049
E/AndroidRuntime(28049): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=content://com.songxing.songxing.ota_update_provider/internal_apk_storage/songxingV1.0.1 flg=0x10000001 }
E/AndroidRuntime(28049): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2117)
E/AndroidRuntime(28049): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1762)
E/AndroidRuntime(28049): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1095)
E/AndroidRuntime(28049): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1066)
E/AndroidRuntime(28049): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:421)
E/AndroidRuntime(28049): 	at sk.fourq.otaupdate.OtaUpdatePlugin.executeInstallation(OtaUpdatePlugin.java:321)
E/AndroidRuntime(28049): 	at sk.fourq.otaupdate.OtaUpdatePlugin.access$200(OtaUpdatePlugin.java:47)
E/AndroidRuntime(28049): 	at sk.fourq.otaupdate.OtaUpdatePlugin$2.run(OtaUpdatePlugin.java:286)
E/AndroidRuntime(28049): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(28049): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28049): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(28049): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(28049): 	at android.app.ActivityThread.main(ActivityThread.java:8250)
E/AndroidRuntime(28049): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28049): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/AndroidRuntime(28049): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by 645638180** [comment]
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (7 months ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1


  ota_update: ^4.0.1

**Comment by MartinHlavna** [comment]
Hello,
what Android version are you testing with?

Thanks

**Comment by 645638180** [comment]
> 你好， 你测试的是什么安卓版本？
> 
> 谢谢

android 12

> Hello, what Android version are you testing with?
> 
> Thanks

android 12

**Comment by MartinHlavna** [comment]
I was not able to reproduce this on android 12. System package manager should handle this intent, there are no changes in Android 12 that should cause it.

Maybe something is preventing it from executing? Can you try with different device?
